### ISSUE TITLE
There is a problem that will happen during my training, I don't know how to solve it.

### ISSUE THREAD

**Issue by zhouwy-lv** [janwithb/carla-gym-wrapper#3]
There is a problem that will happen during my training, I don't know how to solve it.

  File "E:\carla_RL\carla-Ramp\carla_env\carla_env.py", line 340, in step
    next_obs, reward, done, info = self._simulator_step(action)
  File "E:\carla_RL\carla-Ramp\carla_env\carla_env.py", line 398, in _simulator_step
    snapshot, self.display_image = self.sync_mode.tick(timeout=2.0)
  File "E:\carla_RL\carla-Ramp\carla_env\carla_sync_mode.py", line 50, in tick
    data = [self._retrieve_data(q, timeout) for q in self._queues]
  File "E:\carla_RL\carla-Ramp\carla_env\carla_sync_mode.py", line 50, in <listcomp>
    data = [self._retrieve_data(q, timeout) for q in self._queues]
  File "E:\carla_RL\carla-Ramp\carla_env\carla_sync_mode.py", line 69, in _retrieve_data
    data = sensor_queue.get(timeout=timeout)
  File "D:\Anaconda3\Anaconda3\envs\torch_carla\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty

Hope to get your help, thank you.

I use the catch exception to ignore this error, but the pygame interface and the training process will get stuck.

**Comment by zhouwy-lv** [comment]
def get(self, block=True, timeout=None):
        '''Remove and return an item from the queue.

        If optional args 'block' is true and 'timeout' is None (the default),
        block if necessary until an item is available. If 'timeout' is
        a non-negative number, it blocks at most 'timeout' seconds and raises
        the Empty exception if no item was available within that time.
        Otherwise ('block' is false), return an item if one is immediately
        available, else raise the Empty exception ('timeout' is ignored
        in that case).
        '''
        with self.not_empty:
            if not block:
                if not self._qsize():
                    raise Empty
            elif timeout is None:
                while not self._qsize():
                    self.not_empty.wait()
            elif timeout < 0:
                raise ValueError("'timeout' must be a non-negative number")
            else:
                endtime = time() + timeout
                while not self._qsize():
                    remaining = endtime - time()
                    if remaining < 0.0:
                        raise Empty
                    self.not_empty.wait(remaining)
            item = self._get()
            self.not_full.notify()
            return item

The error comes from here.

**Comment by janwithb** [comment]
@zhouwy-lv which CARLA version do you use?

**Comment by zhouwy-lv** [comment]
@janwithb Thanks for your replay! The carla version is 0.9.9. I have solve it through "try ... expect ...", while this method will cause dirty data.
